<a href="https://colab.research.google.com/github/Avazbek-CNU/Gender-Classification/blob/main/Gender_Classification_ipynb%22%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Support Vector Machine (SVM)

Context

Gender is a social construct. The way males and females are treated differently since birth moulds their behaviour and personal preferences into what society expects for their gender.

This small dataset is designed to provide an idea about whether a person's gender can be predicted with an accuracy significantly above 50% based on their personal preferences.

Inspiration

With the rise of feminism, the difference between males and females in terms of their personal preferences has decreased in recent years. For instance, historically in many cultures, warm colors such as red and pink were thought of as feminine colors while cool colors such as blue were considered masculine. Today, such ideas are considered outdated.

Despite the decrease in the influence of gender on people’s personal preferences, can a decent gender classifier be built given a dataset with people’s personal preferences? What does this small dataset suggest?

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [2]:
df=pd.read_csv('Gender Classification.csv')

In [3]:
df.head()

Favorite Color Favorite Music Genre Favorite Beverage Favorite Soft Drink  \
0           Cool                 Rock             Vodka          7UP/Sprite   
1        Neutral              Hip hop             Vodka     Coca Cola/Pepsi   
2           Warm                 Rock              Wine     Coca Cola/Pepsi   
3           Warm     Folk/Traditional           Whiskey               Fanta   
4           Cool                 Rock             Vodka     Coca Cola/Pepsi   

  Gender  
0      F  
1      F  
2      F  
3      F  
4      F

In [4]:
df.shape

(66, 5)

In [5]:
df.isnull().sum()

Favorite Color          0
Favorite Music Genre    0
Favorite Beverage       0
Favorite Soft Drink     0
Gender                  0
dtype: int64

##Convert categorical variables to numeric

In [6]:
df.columns

Index(['Favorite Color', 'Favorite Music Genre', 'Favorite Beverage',
       'Favorite Soft Drink', 'Gender'],
      dtype='object')

In [7]:
df = pd.get_dummies(data=df, columns=['Favorite Color', 'Favorite Music Genre', 'Favorite Beverage',
       'Favorite Soft Drink', 'Gender'])

In [8]:
df.head()

Favorite Color_Cool  Favorite Color_Neutral  Favorite Color_Warm  \
0                    1                       0                    0   
1                    0                       1                    0   
2                    0                       0                    1   
3                    0                       0                    1   
4                    1                       0                    0   

   Favorite Music Genre_Electronic  Favorite Music Genre_Folk/Traditional  \
0                                0                                      0   
1                                0                                      0   
2                                0                                      0   
3                                0                                      1   
4                                0                                      0   

   Favorite Music Genre_Hip hop  Favorite Music Genre_Jazz/Blues  \
0                             0                                0   
1                             1                                0   
2                             0                                0   
3                             0                                0   
4                             0                                0   

   Favorite Music Genre_Pop  Favorite Music Genre_R&B and soul  \
0                         0                                  0   
1                         0                                  0   
2                         0                                  0   
3                         0                                  0   
4                         0                                  0   

   Favorite Music Genre_Rock  ...  Favorite Beverage_Other  \
0                          1  ...                        0   
1                          0  ...                        0   
2                          1  ...                        0   
3                          0  ...                        0   
4                          1  ...                        0   

   Favorite Beverage_Vodka  Favorite Beverage_Whiskey  Favorite Beverage_Wine  \
0                        1                          0                       0   
1                        1                          0                       0   
2                        0                          0                       1   
3                        0                          1                       0   
4                        1                          0                       0   

   Favorite Soft Drink_7UP/Sprite  Favorite Soft Drink_Coca Cola/Pepsi  \
0                               1                                    0   
1                               0                                    1   
2                               0                                    1   
3                               0                                    0   
4                               0                                    1   

   Favorite Soft Drink_Fanta  Favorite Soft Drink_Other  Gender_F  Gender_M  
0                          0                          0         1         0  
1                          0                          0         1         0  
2                          0                          0         1         0  
3                          1                          0         1         0  
4                          0                          0         1         0  

[5 rows x 22 columns]

## Splitting the dataset into the Training set and Test set

In [31]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [32]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [33]:
print(type(X_train))
print(type(X_test))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


## Feature Scaling

In [34]:
from sklearn.preprocessing import StandardScaler

In [35]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

##Training the Logistic Regression model on the Training set

In [38]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

##Predicting the Test set results

In [39]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


##Making the Confusion Matrix

In [40]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 4  0]
 [ 0 10]]


1.0

## Training the SVM model on the Training set

In [42]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [49]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [50]:
from sklearn.svm import SVC

In [51]:
classifier=SVC(kernel='rbf',random_state=0)
classifier.fit(X_train,y_train)

SVC(random_state=0)

## Predicting the Test set results

In [52]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [0 0]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]]


## Making the Confusion Matrix

In [53]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [54]:
cm=confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[ 5  1]
 [ 0 11]]


0.9411764705882353

##K-Nearest Neighbors (K-NN)

In [55]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

##Feature Scaling

In [56]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

##Training the K-NN model on the Training set

In [57]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier()

##Predicting the Test set results

In [58]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [0 0]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]]


##Making the Confusion Matrix

In [59]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 5  1]
 [ 1 10]]


0.8823529411764706

##Support Vector Machine (SVM)

In [71]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

##Feature Scaling

In [72]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

##Training the SVM model on the Training set

In [73]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)

SVC(random_state=0)

##Predicting the Test set results

In [74]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [0 0]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]


##Making the Confusion Matrix

In [75]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 8  1]
 [ 0 11]]


0.95

##Conclusion

In [76]:
from prettytable import PrettyTable

x = PrettyTable(["Model", "Avg Accuracy"])
x.add_row(["LogisticRegression","1"])
x.add_row(["SVM","0.9411764705882353"])
x.add_row(["K-Nearest Neighbors (K-NN)","0.8823529411764706"])
print(x)

+----------------------------+--------------------+
|           Model            |    Avg Accuracy    |
+----------------------------+--------------------+
|     LogisticRegression     |         1          |
|            SVM             | 0.9411764705882353 |
| K-Nearest Neighbors (K-NN) | 0.8823529411764706 |
+----------------------------+--------------------+
